// web/src/features/docx/components/contradiction/ContradictionActionMessageCard.tsx
'use client';

import { ContractChatAssistantIcon, UserIcon } from '@/components/common/icons';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { AssistantChatMessage } from '@/types/document';

interface ContradictionActionMessageCardProps {
	message: AssistantChatMessage;
	rewriteBusy?: boolean;
	compact?: boolean;
	onFocusNodeFromPanel?: (nodeId: string, emphasize?: boolean) => void;
	onAcceptFixSuggestion?: (messageId: string) => void | Promise<void>;
}

/**
 * Contradiction chat action card: shows a structured fix suggestion (changes +
 * original vs rewrite + "Accept suggestion" button) or a free explanation with
 * its snippets. Faithful port of the Svelte `ContradictionActionMessageCard`
 * component.
 */
export function ContradictionActionMessageCard({
	message,
	rewriteBusy = false,
	compact = false,
	onFocusNodeFromPanel = () => {},
	onAcceptFixSuggestion = () => {},
}: ContradictionActionMessageCardProps) {
	const isUserMessage = message.role === 'user';
	const bubbleClass = isUserMessage
		? 'border border-blue-200 bg-blue-50 text-blue-900'
		: 'border border-gray-200 bg-white text-gray-700';

	const fix = message.fixContradictionSuggestion;
	const free = message.freeContradictionExplanation;

	const body = (
		<div
			className={`rounded-lg leading-relaxed shadow-sm ${
				compact ? 'px-2 py-1 text-[10px]' : 'px-2.5 py-2 text-[11px]'
			} ${bubbleClass}`}
		>
			{fix ? (
				<div className="space-y-2">
					<div className="flex flex-wrap items-center justify-between gap-1">
						<div className="flex flex-wrap items-center gap-1">
							<span className="text-[10px] font-bold text-gray-800">
								Structured contradiction fix
							</span>
							<button
								type="button"
								className="docx-reference-chip"
								onClick={() => onFocusNodeFromPanel(fix.paragraphId, true)}
							>
								{fix.paragraphId}
							</button>
						</div>
						{fix.status === 'applied' ? (
							<Badge
								variant="outline"
								className="h-4 border-green-200 bg-green-50 px-1.5 text-[8px] font-semibold text-green-700"
							>
								Applied
							</Badge>
						) : null}
					</div>
					{fix.reason ? <p className="text-[10px] text-gray-700">{fix.reason}</p> : null}
					<div className="rounded border border-gray-200 bg-gray-50/80 px-2 py-1.5">
						<p className="mb-1 text-[9px] font-bold text-gray-700">Changes needed</p>
						<ul className="space-y-1 text-[10px] text-gray-700">
							{fix.changeNotes.map((note, noteIndex) => (
								<li key={`${message.id}-fix-note-${noteIndex}`} className="leading-relaxed">
									• {note}
								</li>
							))}
						</ul>
					</div>
					<div className="overflow-hidden rounded border border-gray-200 bg-white">
						<div className="border-b border-gray-100 bg-red-50/40 px-2 py-1">
							<p className="text-[9px] font-semibold text-red-700">Original Snippet</p>
							<p className="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.originalSnippet}
							</p>
						</div>
						<div className="bg-green-50/40 px-2 py-1">
							<p className="text-[9px] font-semibold text-green-700">Proposed Rewrite</p>
							<p className="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.simplifiedSnippet}
							</p>
						</div>
					</div>
					<Button
						variant="outline"
						size="sm"
						className="h-7 border-green-200 bg-green-50 px-2 text-[10px] font-semibold text-green-700 hover:border-green-300 hover:bg-green-100"
						disabled={rewriteBusy || fix.status === 'applied'}
						onClick={() => void onAcceptFixSuggestion(message.id)}
					>
						{fix.status === 'applied' ? 'Suggestion applied' : 'Accept suggestion'}
					</Button>
				</div>
			) : free ? (
				<div className="space-y-1.5">
					<div className="flex flex-wrap items-center gap-1">
						<span className="font-bold text-gray-800">Free explanation for paragraph</span>
					</div>
					<p className="text-[10px] text-gray-700">{free.reason}</p>
					{free.snippetA && free.snippetB ? (
						<>
							<div className="space-y-1">
								<p className="text-[10px] font-bold text-red-700">
									Snippet A ({free.snippetA.source}):
								</p>
								<p className="rounded border border-red-300 bg-red-100/70 px-2 py-1 text-[10px] text-red-900">
									&quot;{free.snippetA.text}&quot;
								</p>
							</div>
							<div className="space-y-1">
								<p className="text-[10px] font-bold text-yellow-700">
									Snippet B ({free.snippetB.source}):
								</p>
								<p className="rounded border border-yellow-300 bg-yellow-100/75 px-2 py-1 text-[10px] text-yellow-900">
									&quot;{free.snippetB.text}&quot;
								</p>
							</div>
						</>
					) : free.fallbackEvidenceMessage ? (
						<p className="text-[10px] text-gray-600">{free.fallbackEvidenceMessage}</p>
					) : null}
					<p className="text-[10px] text-gray-600">{free.footerMessage}</p>
				</div>
			) : null}
		</div>
	);

	const icon = isUserMessage ? (
		<span className="mt-1 inline-flex shrink-0 items-center justify-center text-blue-600">
			<UserIcon className={compact ? 'h-3.5 w-3.5' : 'h-4 w-4'} strokeWidth={1.9} />
			<span className="sr-only">You</span>
		</span>
	) : (
		<span className="mt-1 inline-flex shrink-0 items-center justify-center text-gray-500">
			<ContractChatAssistantIcon className={compact ? 'h-3.5 w-3.5' : 'h-4 w-4'} strokeWidth={1.9} />
			<span className="sr-only">Assistant</span>
		</span>
	);

	return (
		<div className="inline-flex max-w-[92%] items-start gap-1.5">
			{isUserMessage ? (
				<>
					{body}
					{icon}
				</>
			) : (
				<>
					{icon}
					{body}
				</>
			)}
		</div>
	);
}

// client/src/lib/components/docx/ContradictionActionMessageCard.svelte
<script lang="ts">
	import type { AssistantChatMessage } from '$lib/types/document';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import ContractChatAssistantIcon from '$lib/icons/ContractChatAssistantIcon.svelte';
	import UserIcon from '$lib/icons/UserIcon.svelte';

	export let message: AssistantChatMessage;
	export let rewriteBusy = false;
	export let compact = false;
	export let onFocusNodeFromPanel: (nodeId: string, emphasize?: boolean) => void = () => {};
	export let onAcceptFixSuggestion: (messageId: string) => void | Promise<void> = () => {};

	$: isUserMessage = message.role === 'user';
	$: bubbleClass = isUserMessage
		? 'border border-blue-200 bg-blue-50 text-blue-900'
		: 'border border-gray-200 bg-white text-gray-700';
</script>

<div class="inline-flex max-w-[92%] items-start gap-1.5">
	{#if isUserMessage}
		<div
			class={`rounded-lg leading-relaxed shadow-sm ${
				compact ? 'px-2 py-1 text-[10px]' : 'px-2.5 py-2 text-[11px]'
			} ${bubbleClass}`}
		>
			{#if message.fixContradictionSuggestion}
				{@const fix = message.fixContradictionSuggestion}
				<div class="space-y-2">
					<div class="flex flex-wrap items-center justify-between gap-1">
						<div class="flex flex-wrap items-center gap-1">
							<span class="text-[10px] font-bold text-gray-800">Structured contradiction fix</span>
							<button
								type="button"
								class="docx-reference-chip"
								onclick={() => onFocusNodeFromPanel(fix.paragraphId, true)}
							>
								{fix.paragraphId}
							</button>
						</div>
						{#if fix.status === 'applied'}
							<Badge
								variant="outline"
								class="h-4 border-green-200 bg-green-50 px-1.5 text-[8px] font-semibold text-green-700"
							>
								Applied
							</Badge>
						{/if}
					</div>
					{#if fix.reason}
						<p class="text-[10px] text-gray-700">{fix.reason}</p>
					{/if}
					<div class="rounded border border-gray-200 bg-gray-50/80 px-2 py-1.5">
						<p class="mb-1 text-[9px] font-bold text-gray-700">Changes needed</p>
						<ul class="space-y-1 text-[10px] text-gray-700">
							{#each fix.changeNotes as note, noteIndex (`${message.id}-fix-note-${noteIndex}`)}
								<li class="leading-relaxed">• {note}</li>
							{/each}
						</ul>
					</div>
					<div class="overflow-hidden rounded border border-gray-200 bg-white">
						<div class="border-b border-gray-100 bg-red-50/40 px-2 py-1">
							<p class="text-[9px] font-semibold text-red-700">Original Snippet</p>
							<p class="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.originalSnippet}
							</p>
						</div>
						<div class="bg-green-50/40 px-2 py-1">
							<p class="text-[9px] font-semibold text-green-700">Proposed Rewrite</p>
							<p class="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.simplifiedSnippet}
							</p>
						</div>
					</div>
					<Button
						variant="outline"
						size="sm"
						class="h-7 border-green-200 bg-green-50 px-2 text-[10px] font-semibold text-green-700 hover:border-green-300 hover:bg-green-100"
						disabled={rewriteBusy || fix.status === 'applied'}
						onclick={() => void onAcceptFixSuggestion(message.id)}
					>
						{fix.status === 'applied' ? 'Suggestion applied' : 'Accept suggestion'}
					</Button>
				</div>
			{:else if message.freeContradictionExplanation}
				{@const free = message.freeContradictionExplanation}
				<div class="space-y-1.5">
					<div class="flex flex-wrap items-center gap-1">
						<span class="font-bold text-gray-800">Free explanation for paragraph</span>
					</div>
					<p class="text-[10px] text-gray-700">{free.reason}</p>
					{#if free.snippetA && free.snippetB}
						<div class="space-y-1">
							<p class="text-[10px] font-bold text-red-700">Snippet A ({free.snippetA.source}):</p>
							<p class="rounded border border-red-300 bg-red-100/70 px-2 py-1 text-[10px] text-red-900">
								"{free.snippetA.text}"
							</p>
						</div>
						<div class="space-y-1">
							<p class="text-[10px] font-bold text-yellow-700">Snippet B ({free.snippetB.source}):</p>
							<p
								class="rounded border border-yellow-300 bg-yellow-100/75 px-2 py-1 text-[10px] text-yellow-900"
							>
								"{free.snippetB.text}"
							</p>
						</div>
					{:else if free.fallbackEvidenceMessage}
						<p class="text-[10px] text-gray-600">{free.fallbackEvidenceMessage}</p>
					{/if}
					<p class="text-[10px] text-gray-600">{free.footerMessage}</p>
				</div>
			{/if}
		</div>
		<span class="mt-1 inline-flex shrink-0 items-center justify-center text-blue-600">
			<UserIcon className={compact ? 'h-3.5 w-3.5' : 'h-4 w-4'} strokeWidth={1.9} />
			<span class="sr-only">You</span>
		</span>
	{:else}
		<span class="mt-1 inline-flex shrink-0 items-center justify-center text-gray-500">
			<ContractChatAssistantIcon className={compact ? 'h-3.5 w-3.5' : 'h-4 w-4'} strokeWidth={1.9} />
			<span class="sr-only">Assistant</span>
		</span>
		<div
			class={`rounded-lg leading-relaxed shadow-sm ${
				compact ? 'px-2 py-1 text-[10px]' : 'px-2.5 py-2 text-[11px]'
			} ${bubbleClass}`}
		>
			{#if message.fixContradictionSuggestion}
				{@const fix = message.fixContradictionSuggestion}
				<div class="space-y-2">
					<div class="flex flex-wrap items-center justify-between gap-1">
						<div class="flex flex-wrap items-center gap-1">
							<span class="text-[10px] font-bold text-gray-800">Structured contradiction fix</span>
							<button
								type="button"
								class="docx-reference-chip"
								onclick={() => onFocusNodeFromPanel(fix.paragraphId, true)}
							>
								{fix.paragraphId}
							</button>
						</div>
						{#if fix.status === 'applied'}
							<Badge
								variant="outline"
								class="h-4 border-green-200 bg-green-50 px-1.5 text-[8px] font-semibold text-green-700"
							>
								Applied
							</Badge>
						{/if}
					</div>
					{#if fix.reason}
						<p class="text-[10px] text-gray-700">{fix.reason}</p>
					{/if}
					<div class="rounded border border-gray-200 bg-gray-50/80 px-2 py-1.5">
						<p class="mb-1 text-[9px] font-bold text-gray-700">Changes needed</p>
						<ul class="space-y-1 text-[10px] text-gray-700">
							{#each fix.changeNotes as note, noteIndex (`${message.id}-fix-note-${noteIndex}`)}
								<li class="leading-relaxed">• {note}</li>
							{/each}
						</ul>
					</div>
					<div class="overflow-hidden rounded border border-gray-200 bg-white">
						<div class="border-b border-gray-100 bg-red-50/40 px-2 py-1">
							<p class="text-[9px] font-semibold text-red-700">Original Snippet</p>
							<p class="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.originalSnippet}
							</p>
						</div>
						<div class="bg-green-50/40 px-2 py-1">
							<p class="text-[9px] font-semibold text-green-700">Proposed Rewrite</p>
							<p class="mt-0.5 text-[10px] leading-relaxed text-gray-900">
								{fix.rewriteResult.payload.simplifiedSnippet}
							</p>
						</div>
					</div>
					<Button
						variant="outline"
						size="sm"
						class="h-7 border-green-200 bg-green-50 px-2 text-[10px] font-semibold text-green-700 hover:border-green-300 hover:bg-green-100"
						disabled={rewriteBusy || fix.status === 'applied'}
						onclick={() => void onAcceptFixSuggestion(message.id)}
					>
						{fix.status === 'applied' ? 'Suggestion applied' : 'Accept suggestion'}
					</Button>
				</div>
			{:else if message.freeContradictionExplanation}
				{@const free = message.freeContradictionExplanation}
				<div class="space-y-1.5">
					<div class="flex flex-wrap items-center gap-1">
						<span class="font-bold text-gray-800">Free explanation for paragraph</span>
					</div>
					<p class="text-[10px] text-gray-700">{free.reason}</p>
					{#if free.snippetA && free.snippetB}
						<div class="space-y-1">
							<p class="text-[10px] font-bold text-red-700">Snippet A ({free.snippetA.source}):</p>
							<p class="rounded border border-red-300 bg-red-100/70 px-2 py-1 text-[10px] text-red-900">
								"{free.snippetA.text}"
							</p>
						</div>
						<div class="space-y-1">
							<p class="text-[10px] font-bold text-yellow-700">Snippet B ({free.snippetB.source}):</p>
							<p
								class="rounded border border-yellow-300 bg-yellow-100/75 px-2 py-1 text-[10px] text-yellow-900"
							>
								"{free.snippetB.text}"
							</p>
						</div>
					{:else if free.fallbackEvidenceMessage}
						<p class="text-[10px] text-gray-600">{free.fallbackEvidenceMessage}</p>
					{/if}
					<p class="text-[10px] text-gray-600">{free.footerMessage}</p>
				</div>
			{/if}
		</div>
	{/if}
</div>
