// web/src/features/docx/components/contradiction/RightPanelAnalysis.tsx
'use client';

import type { ReactNode } from 'react';
import { ProcessingIndicator } from '@/components/common/ProcessingIndicator';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
	CONTRADICTION_TAXONOMY_COLORS,
	CONTRADICTION_TAXONOMY_LABELS,
	CONTRADICTION_TAXONOMY_ORDER,
} from '@/constants/docx-viewer';
import type {
	ContradictionParagraphResult,
	ContradictionTaxonomyType,
	Node as ParagraphNode,
} from '@/types/document';

import { ContradictionSummary } from '@/features/docx/components/contradiction/ContradictionSummary';

interface RightPanelAnalysisProps {
	selectedParagraph: ParagraphNode | null;
	contradictionLoading: boolean;
	hasTriggeredContradictionCheck: boolean;
	contradictionError: string | null;
	contradictionCount: number;
	contradictionSummaryItems: {
		paragraphId: string;
		label: string;
		contradictionType: ContradictionTaxonomyType;
	}[];
	selectedContradictionResult: ContradictionParagraphResult | null;
	selectedContradictionEvidence: ContradictionParagraphResult['evidence'];
	onFocusEvidenceSnippet: (paragraphId: string, role: 'a' | 'b') => void;
	onFocusNodeFromPanel: (nodeId: string, emphasize?: boolean) => void;
	/** Assistant chat panel, anchored at the bottom. */
	chatSlot?: ReactNode;
}

const CONTRADICTION_PROCESSING_STEPS = [
	{ label: 'Reading the selected paragraph', active: true },
	{ label: 'Comparing against related clauses', active: false },
	{ label: 'Detecting contradictions', active: false },
];

/**
 * Right-side analysis panel: inspects contradictions, confidence, and evidence
 * for the selected paragraph. Ported from the contradiction-display half of the
 * Svelte `RightPanelAnalysis` component. The chat/assistant half is stubbed.
 */
export function RightPanelAnalysis({
	selectedParagraph,
	contradictionLoading,
	hasTriggeredContradictionCheck,
	contradictionError,
	contradictionCount,
	contradictionSummaryItems,
	selectedContradictionResult,
	selectedContradictionEvidence,
	onFocusEvidenceSnippet,
	onFocusNodeFromPanel,
	chatSlot,
}: RightPanelAnalysisProps) {
	return (
		<section className="flex min-h-0 flex-1 flex-col">
			<header className="border-b border-gray-100 bg-gray-50 px-4 py-2">
				<p className="text-[11px] text-gray-500">
					Inspect contradictions, confidence, and evidence for the selected paragraph.
				</p>
			</header>

			<ScrollArea className="min-h-0 flex-1">
				<div className="flex min-h-full flex-col gap-1 p-3">
					{contradictionLoading ? (
						<ProcessingIndicator steps={CONTRADICTION_PROCESSING_STEPS} />
					) : null}

					{hasTriggeredContradictionCheck ? (
						contradictionError ? (
							<p className="text-[11px] text-red-700">{contradictionError}</p>
						) : (
							<div className="flex flex-col gap-1">
								<p className="text-[11px] text-blue-600">
									{contradictionCount} paragraph(s) with highlighted contradiction(s)
								</p>
								<div className="flex flex-wrap items-center gap-1.5">
									{CONTRADICTION_TAXONOMY_ORDER.map((category) => (
										<span
											key={category}
											className="inline-flex items-center gap-1 rounded border border-gray-200 bg-white px-1.5 py-0.5 text-[9px] text-gray-600"
											title={CONTRADICTION_TAXONOMY_LABELS[category]}
										>
											<span
												className="inline-block h-1.5 w-1.5 rounded-full"
												style={{ background: CONTRADICTION_TAXONOMY_COLORS[category] }}
											/>
											{CONTRADICTION_TAXONOMY_LABELS[category]}
										</span>
									))}
								</div>
							</div>
						)
					) : null}

					{contradictionSummaryItems.length > 0 ? (
						<ContradictionSummary
							selectedParagraph={selectedParagraph}
							contradictionSummaryItems={contradictionSummaryItems}
							selectedContradictionResult={selectedContradictionResult}
							selectedContradictionEvidence={selectedContradictionEvidence}
							onFocusEvidenceSnippet={onFocusEvidenceSnippet}
							onFocusNodeFromPanel={onFocusNodeFromPanel}
						/>
					) : hasTriggeredContradictionCheck && !contradictionLoading && !contradictionError ? (
						<div className="flex flex-col items-center justify-center py-2 text-gray-400">
							<p className="text-[10px] italic">No contradictions found.</p>
						</div>
					) : null}
				</div>
			</ScrollArea>

			{/* Chat/assistant panel anchored at the bottom (controls its own height). */}
			{chatSlot}
		</section>
	);
}

// client/src/lib/components/docx/RightPanelAnalysis.svelte
<script lang="ts">
	import type { ContradictionParagraphResult, Node as ParagraphNode } from '$lib/types/document';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { ScrollArea } from '$lib/components/ui/scroll-area/index.js';

	type ProcessingStep = {
		label: string;
		active: boolean;
	};

	export let selectedParagraph: ParagraphNode | null = null;
	export let contradictionLoading = false;
	export let revisionProcessingSteps: ProcessingStep[] = [];
	export let selectedContradictionResult: ContradictionParagraphResult | null = null;
	export let selectedContradictionEvidence: ContradictionParagraphResult['evidence'] = null;
	export let onFocusEvidenceSnippet: (paragraphId: string, role: 'a' | 'b') => void = () => {};
</script>

<section class="flex min-h-0 flex-1 flex-col">
	<header class="border-b border-gray-100 bg-gray-50 px-4 py-2">
		<p class="text-[11px] text-gray-500">
			Inspect contradictions, confidence, and evidence for the selected paragraph.
		</p>
	</header>

	<ScrollArea class="min-h-0 flex-1">
		<div class="space-y-2 p-3">
			{#if contradictionLoading}
				<div class="rounded-xl border border-gray-200 bg-gray-50/90 p-3 text-[11px] text-gray-700">
					<p class="mb-2 text-[10px] font-semibold text-gray-500">Processing panel</p>
					<ul class="space-y-1.5 text-[12px] text-gray-600">
						{#each revisionProcessingSteps as step, index}
							<li
								class="flex [animation:processing-step-fade_1.35s_ease-in-out_infinite] items-center gap-2 opacity-[0.45]"
								style={`animation-delay: ${index * 220}ms;`}
							>
								<span
									class="h-1.5 w-1.5 [animation:processing-dot-pulse_1.2s_ease-in-out_infinite] rounded-full bg-gray-500 opacity-[0.35]"
									style={`animation-delay: ${index * 220}ms;`}
									aria-hidden="true"
								></span>
								<span class="text-gray-600">
									{step.label}
									<span class="ml-px inline-flex min-w-[14px]" aria-hidden="true">
										<span
											class="[animation:processing-ellipsis-dot_0.95s_ease-in-out_infinite] opacity-[0.18]"
											style="animation-delay: 0ms;">.</span
										>
										<span
											class="[animation:processing-ellipsis-dot_0.95s_ease-in-out_infinite] opacity-[0.18]"
											style="animation-delay: 140ms;">.</span
										>
										<span
											class="[animation:processing-ellipsis-dot_0.95s_ease-in-out_infinite] opacity-[0.18]"
											style="animation-delay: 280ms;">.</span
										>
									</span>
								</span>
							</li>
						{/each}
					</ul>
				</div>
			{/if}

			{#if !selectedParagraph}
				<div class="flex flex-col items-center justify-center py-3 text-center text-gray-400">
					<p class="text-[10px] font-medium">Select a paragraph to analyze contradictions</p>
					<p class="mt-1 text-[10px] text-gray-400">
						Choose a paragraph in the document on the left.
					</p>
				</div>
			{:else if !selectedContradictionResult}
				<Card.Root size="sm" class="border-gray-200 bg-gray-50 py-0 text-[11px]">
					<Card.Content class="px-3 py-2 text-gray-600">
						No contradiction result is available for this paragraph yet. Run "Search contradictions"
						first.
					</Card.Content>
				</Card.Root>
			{:else if !selectedContradictionResult.contradiction}
				<div class="flex flex-col items-center justify-center py-3 text-center text-gray-400">
					<p class="text-[10px] italic">No contradiction found in this paragraph.</p>
				</div>
			{:else}
				<Card.Root size="sm" class="border-red-200 bg-red-50/65 py-0 text-[11px]">
					<Card.Content class="px-3 py-2 text-red-800">
						<p>
							Confidence: {selectedContradictionResult.confidence}% · {selectedContradictionResult.brief_reason}
						</p>
					</Card.Content>
				</Card.Root>

				{#if selectedContradictionEvidence?.snippet_a?.trim() && selectedContradictionEvidence?.snippet_b?.trim()}
					<div class="overflow-hidden rounded border border-red-200 bg-red-50/70 text-[11px]">
						<div class="border-b border-red-200 bg-red-100/70 px-3 py-1.5">
							<p class="text-[9px] font-semibold text-red-700">Contradiction evidence</p>
						</div>
						<div class="space-y-2 p-2.5">
							<div class="rounded border border-red-300 bg-red-100/80 px-2.5 py-2">
								<div class="mb-1 flex items-center justify-between">
									<span class="text-[9px] font-semibold text-red-800">Snippet A</span>
									<Badge
										variant="outline"
										class="h-4 border-red-300 bg-white px-1.5 text-[8px] font-semibold text-red-800"
									>
										{selectedContradictionEvidence.source_a}
									</Badge>
								</div>
								<Button
									variant="ghost"
									class="h-auto w-full min-w-0 items-start justify-start whitespace-normal break-words [overflow-wrap:anywhere] px-0 py-0 text-left leading-relaxed text-red-800 hover:bg-transparent hover:text-red-900"
									onclick={() =>
										selectedContradictionResult &&
										onFocusEvidenceSnippet(selectedContradictionResult.paragraph_id, 'a')}
								>
									{selectedContradictionEvidence.snippet_a}
								</Button>
							</div>

							<div class="rounded border border-red-300 bg-red-100/80 px-2.5 py-2">
								<div class="mb-1 flex items-center justify-between">
									<span class="text-[9px] font-semibold text-red-800">Snippet B</span>
									<Badge
										variant="outline"
										class="h-4 border-red-300 bg-white px-1.5 text-[8px] font-semibold text-red-800"
									>
										{selectedContradictionEvidence.source_b}
									</Badge>
								</div>
								<Button
									variant="ghost"
									class="h-auto w-full min-w-0 items-start justify-start whitespace-normal break-words [overflow-wrap:anywhere] px-0 py-0 text-left leading-relaxed text-red-800 hover:bg-transparent hover:text-red-900"
									onclick={() =>
										selectedContradictionResult &&
										onFocusEvidenceSnippet(selectedContradictionResult.paragraph_id, 'b')}
								>
									{selectedContradictionEvidence.snippet_b}
								</Button>
							</div>
						</div>
					</div>
				{:else}
					<Card.Root size="sm" class="border-gray-200 bg-gray-50 py-0 text-[11px]">
						<Card.Content class="px-3 py-2 text-gray-600">
							Evidence snippets are unavailable for this contradiction.
						</Card.Content>
					</Card.Root>
				{/if}
			{/if}
		</div>
	</ScrollArea>
</section>
